clear all
close all
clc

model = 'vctree';
dataset = 'vg';

setting_arr = ["predcls", "sgcls", "sgdet"];

for s = 1:length(setting_arr)
    setting = setting_arr(s);
    suffix = strcat(model,'_',setting,'_',dataset);

    datapath = strcat('..\Data\',dataset,'\',model,'\',setting,'\');


    %loading measurement results from baseline model
    load(strcat(datapath,'data_rel_meas_infer_',suffix,'.mat'))
    %loading ground truth results
    load(strcat(datapath,'data_rel_ground_',suffix,'.mat'))
    
    if strcmp(setting,'sgdet') && strcmp(dataset,'vg') 
        [predicate_logits_list, obj_logits_list] = combine_sgdet_probs(datapath,suffix);
    end
    
    %loading dictionary file for VG or GQA
    if strcmp(dataset, 'vg')
        dict = jsondecode(fileread('VG-SGG-dicts.json'));
    end
    if strcmp(dataset, 'gqa')
       dict = jsondecode(fileread('GQA-SGG-dicts.json'));
    end 
    
    
    
    %You can perform testing with full dataset or partial dataset
    test_start = 1;
    test_end = length(ground_box_list);
    top_list = [20, 50, 100];
    for i = 1:length(top_list)
        top = top_list(i);
        
        
        %Evaluating measurement results
        title_part = 'measured';
        [recall_meas,mean_recall_meas,correct_relations_measured,correct_relations_measured_all,total_ground_truth_relations_all,recall_meas_per_rel,cat_IA_cat,measured_aligned_triplets] = compute_recalls(measured_triplets,measured_triplets_box_list,ground_rel_data,ground_triplets_box_list,test_start,test_end,top,dict,title_part);
        
        
        
        % In this stage, we will perform within triplet inference with prior
        % learnt from origial samples
        method = 'org';
        title_part = 'inferred-org';
        if strcmp(setting,'sgcls') || strcmp(setting,'sgdet')
            [inferred_triplets] = infer_triplets(measured_triplets,measured_relations_list,obj_logits_list,predicate_logits_list,top,test_start,test_end,method,dataset);
            [resoluted_inferred_triplets] = resolute_conflict(inferred_triplets,measured_triplets,measured_relations_list,predicate_logits_list,obj_logits_list,measured_label_list,test_start,test_end,top,method,dataset);
            [recall_infer,mean_recall_infer,correct_relations_inferred,correct_relations_inferred_all,total_ground_truth_relations_all,recall_infer_per_rel,cat_IA_cat,inferred_aligned_triplets] = compute_recalls(resoluted_inferred_triplets,measured_triplets_box_list,ground_rel_data,ground_triplets_box_list,test_start,test_end,top,dict,title_part);
        elseif strcmp(setting,'predcls')
            [inferred_triplets] = infer_triplets_conditional(measured_triplets,predicate_logits_list,top,test_start,test_end,method,dataset);
            [recall_infer,mean_recall_infer,correct_relations_inferred,correct_relations_inferred_all,total_ground_truth_relations_all,recall_infer_per_rel,cat_IA_cat,inferred_aligned_triplets] = compute_recalls(inferred_triplets,measured_triplets_box_list,ground_rel_data,ground_triplets_box_list,test_start,test_end,top,dict,title_part);
        end
        
        % In this stage, we will perform within triplet inference with prior
        % learnt from augmented samples
        method = 'aug';
        title_part = 'inferred-aug';
        if strcmp(setting,'sgcls') || strcmp(setting,'sgdet')
            [inferred_triplets_emb] = infer_triplets(measured_triplets,measured_relations_list,obj_logits_list,predicate_logits_list,top,test_start,test_end,method,dataset);
            [resoluted_inferred_triplets_emb] = resolute_conflict(inferred_triplets_emb,measured_triplets,measured_relations_list,predicate_logits_list,obj_logits_list,measured_label_list,test_start,test_end,top,method,dataset);
            [recall_infer_emb,mean_recall_infer_emb,correct_relations_inferred_emb,correct_relations_inferred_all_emb,total_ground_truth_relations_all,recall_infer_emb_per_rel,cat_IA_cat,inferred_aligned_triplets] = compute_recalls(resoluted_inferred_triplets_emb,measured_triplets_box_list,ground_rel_data,ground_triplets_box_list,test_start,test_end,top,dict,title_part);    
        elseif strcmp(setting,'predcls')
            [inferred_triplets_emb] = infer_triplets_conditional(measured_triplets,predicate_logits_list,top,test_start,test_end,method,dataset);
            [recall_infer_emb,mean_recall_infer_emb,correct_relations_inferred_emb,correct_relations_inferred_all_emb,total_ground_truth_relations_all,recall_infer_emb_per_rel,cat_IA_cat,inferred_aligned_triplets] = compute_recalls(inferred_triplets_emb,measured_triplets_box_list,ground_rel_data,ground_triplets_box_list,test_start,test_end,top,dict,title_part);    
        end
        
        
        recall_meas_arr(i,s) = recall_meas;
        recall_infer_arr(i,s) = recall_infer;
        recall_infer_emb_arr(i,s) = recall_infer_emb;
        
        mean_recall_meas_arr(i,s) = mean_recall_meas;
        mean_recall_infer_arr(i,s) = mean_recall_infer;
        mean_recall_infer_emb_arr(i,s) = mean_recall_infer_emb;
    
    
    end
    
    
end

recall_meas_arr = recall_meas_arr*100;
recall_infer_arr = recall_infer_arr*100;
recall_infer_emb_arr = recall_infer_emb_arr*100;

mean_recall_meas_arr = mean_recall_meas_arr*100;
mean_recall_infer_arr = mean_recall_infer_arr*100;
mean_recall_infer_emb_arr = mean_recall_infer_emb_arr*100;

%Display Results for Main Part @50/100
disp(strcat("Measurements: ",num2str(recall_meas_arr(2,1),'%0.2f'), ...
    "/ ",num2str(recall_meas_arr(3,1),'%0.2f'), ...
    " & ",num2str(mean_recall_meas_arr(2,1),'%0.2f'), ...
    "/ ",num2str(mean_recall_meas_arr(3,1),'%0.2f'),...
    " & ",num2str(recall_meas_arr(2,2),'%0.2f'), ...
    "/ ",num2str(recall_meas_arr(3,2),'%0.2f'),...
    " & ",num2str(mean_recall_meas_arr(2,2),'%0.2f'), ...
    "/ ",num2str(mean_recall_meas_arr(3,2),'%0.2f'),...
     " & ",num2str(recall_meas_arr(2,3),'%0.2f'), ...
    "/ ",num2str(recall_meas_arr(3,3),'%0.2f'),...
    " & ",num2str(mean_recall_meas_arr(2,3),'%0.2f'), ...
    "/ ",num2str(mean_recall_meas_arr(3,3),'%0.2f')))

disp(strcat("Inf (Org): ",num2str(recall_infer_arr(2,1),'%0.2f'), ...
    "/ ",num2str(recall_infer_arr(3,1),'%0.2f'), ...
    " & ",num2str(mean_recall_infer_arr(2,1),'%0.2f'), ...
    "/ ",num2str(mean_recall_infer_arr(3,1),'%0.2f'),...
    " & ",num2str(recall_infer_arr(2,2),'%0.2f'), ...
    "/ ",num2str(recall_infer_arr(3,2),'%0.2f'),...
    " & ",num2str(mean_recall_infer_arr(2,2),'%0.2f'), ...
    "/ ",num2str(mean_recall_infer_arr(3,2),'%0.2f'),...
     " & ",num2str(recall_infer_arr(2,3),'%0.2f'), ...
    "/ ",num2str(recall_infer_arr(3,3),'%0.2f'),...
    " & ",num2str(mean_recall_infer_arr(2,3),'%0.2f'), ...
    "/ ",num2str(mean_recall_infer_arr(3,3),'%0.2f')))


disp(strcat("Inf (Aug): ",num2str(recall_infer_emb_arr(2,1),'%0.2f'), ...
    "/ ",num2str(recall_infer_emb_arr(3,1),'%0.2f'), ...
    " & ",num2str(mean_recall_infer_emb_arr(2,1),'%0.2f'), ...
    "/ ",num2str(mean_recall_infer_emb_arr(3,1),'%0.2f'),...
    " & ",num2str(recall_infer_emb_arr(2,2),'%0.2f'), ...
    "/ ",num2str(recall_infer_emb_arr(3,2),'%0.2f'),...
    " & ",num2str(mean_recall_infer_emb_arr(2,2),'%0.2f'), ...
    "/ ",num2str(mean_recall_infer_emb_arr(3,2),'%0.2f'),...
     " & ",num2str(recall_infer_emb_arr(2,3),'%0.2f'), ...
    "/ ",num2str(recall_infer_emb_arr(3,3),'%0.2f'),...
    " & ",num2str(mean_recall_infer_emb_arr(2,3),'%0.2f'), ...
    "/ ",num2str(mean_recall_infer_emb_arr(3,3),'%0.2f')))




%Display Results for Supple Part @20/50/100
disp(strcat("Measurements: ",num2str(recall_meas_arr(1,1),'%0.1f'), ...
    "/ ",num2str(recall_meas_arr(2,1),'%0.1f'), ...
    "/ ",num2str(recall_meas_arr(3,1),'%0.1f'), ...
    " & ",num2str(mean_recall_meas_arr(1,1),'%0.1f'), ...
    "/ ",num2str(mean_recall_meas_arr(2,1),'%0.1f'), ...
    "/ ",num2str(mean_recall_meas_arr(3,1),'%0.1f'),...
    " & ",num2str(recall_meas_arr(1,2),'%0.1f'), ...
    "/ ",num2str(recall_meas_arr(2,2),'%0.1f'), ...
    "/ ",num2str(recall_meas_arr(3,2),'%0.1f'),...
    " & ",num2str(mean_recall_meas_arr(1,2),'%0.1f'), ...
    "/ ",num2str(mean_recall_meas_arr(2,2),'%0.1f'), ...
    "/ ",num2str(mean_recall_meas_arr(3,2),'%0.1f'),...
    " & ",num2str(recall_meas_arr(1,3),'%0.1f'), ...
    "/ ",num2str(recall_meas_arr(2,3),'%0.1f'), ...
    "/ ",num2str(recall_meas_arr(3,3),'%0.1f'),...
    " & ",num2str(mean_recall_meas_arr(1,3),'%0.1f'), ...
    "/ ",num2str(mean_recall_meas_arr(2,3),'%0.1f'), ...
    "/ ",num2str(mean_recall_meas_arr(3,3),'%0.1f')))

disp(strcat("Inf (Org): ",num2str(recall_infer_arr(1,1),'%0.1f'), ...
    "/ ",num2str(recall_infer_arr(2,1),'%0.1f'), ...
    "/ ",num2str(recall_infer_arr(3,1),'%0.1f'), ...
    " & ",num2str(mean_recall_infer_arr(1,1),'%0.1f'), ...
    "/ ",num2str(mean_recall_infer_arr(2,1),'%0.1f'), ...
    "/ ",num2str(mean_recall_infer_arr(3,1),'%0.1f'),...
    " & ",num2str(recall_infer_arr(1,2),'%0.1f'), ...
    "/ ",num2str(recall_infer_arr(2,2),'%0.1f'), ...
    "/ ",num2str(recall_infer_arr(3,2),'%0.1f'),...
    " & ",num2str(mean_recall_infer_arr(1,2),'%0.1f'), ...
    "/ ",num2str(mean_recall_infer_arr(2,2),'%0.1f'), ...
    "/ ",num2str(mean_recall_infer_arr(3,2),'%0.1f'),...
    " & ",num2str(recall_infer_arr(1,3),'%0.1f'), ...
    "/ ",num2str(recall_infer_arr(2,3),'%0.1f'), ...
    "/ ",num2str(recall_infer_arr(3,3),'%0.1f'),...
    " & ",num2str(mean_recall_infer_arr(1,3),'%0.1f'), ...
    "/ ",num2str(mean_recall_infer_arr(2,3),'%0.1f'), ...
    "/ ",num2str(mean_recall_infer_arr(3,3),'%0.1f')))

disp(strcat("Inf (Aug): ",num2str(recall_infer_emb_arr(1,1),'%0.1f'), ...
    "/ ",num2str(recall_infer_emb_arr(2,1),'%0.1f'), ...
    "/ ",num2str(recall_infer_emb_arr(3,1),'%0.1f'), ...
    " & ",num2str(mean_recall_infer_emb_arr(1,1),'%0.1f'), ...
    "/ ",num2str(mean_recall_infer_emb_arr(2,1),'%0.1f'), ...
    "/ ",num2str(mean_recall_infer_emb_arr(3,1),'%0.1f'),...
    " & ",num2str(recall_infer_emb_arr(1,2),'%0.1f'), ...
    "/ ",num2str(recall_infer_emb_arr(2,2),'%0.1f'), ...
    "/ ",num2str(recall_infer_emb_arr(3,2),'%0.1f'),...
    " & ",num2str(mean_recall_infer_emb_arr(1,2),'%0.1f'), ...
    "/ ",num2str(mean_recall_infer_emb_arr(2,2),'%0.1f'), ...
    "/ ",num2str(mean_recall_infer_emb_arr(3,2),'%0.1f'),...
    " & ",num2str(recall_infer_emb_arr(1,3),'%0.1f'), ...
    "/ ",num2str(recall_infer_emb_arr(2,3),'%0.1f'), ...
    "/ ",num2str(recall_infer_emb_arr(3,3),'%0.1f'),...
    " & ",num2str(mean_recall_infer_emb_arr(1,3),'%0.1f'), ...
    "/ ",num2str(mean_recall_infer_emb_arr(2,3),'%0.1f'), ...
    "/ ",num2str(mean_recall_infer_emb_arr(3,3),'%0.1f')))

